### ISSUE TITLE
Hello Group, question:

### ISSUE THREAD

**Issue by pablospanish9** [Ksynlsn/it115-a3#16]
Hello Group, question:
Do we create a new branch from the original, main, every time? It looks like sometimes we are creating new branches from a branched version. I don't know the difference between the green, blue, and purple arrows: https://github.com/Ksynlsn/it115-a3/network
Here are the instructions, but it is not clear to me:
1. Create a named branch, make a change/addition to the story
2. Create a pull request to indicate you'd like a second pair of eyes to view/edit your addition
3. The second person changes/approves the change and merges the change.
4. The second person starts a new branch and begins the process again, with the next person on your team.

_Originally posted by @pablospanish9 in https://github.com/Ksynlsn/it115-a3/issues/14#issuecomment-1282599790_

**Comment by nvialp** [comment]
Morning Everyone,
I also have been skipped on the review and merge task.  Currently the next branch was created by Kacie and she assigned Brandon for review.

**Comment by Ksynlsn** [comment]
Yes, I think we should be making a new branch, from main, each time.

**Comment by Ksynlsn** [comment]
@marissadashen and @nvialp - I added both of you to the 'assigned ' people on this most recent pull request. That way, whoever gets to it and merges it first could make the next branch, and assign it to the other? That way you both can have at least one more commit.

**Comment by nvialp** [comment]
Thank you Kacie for coordinating.  I reviewed and merged Marissa's 15th stanza, created 16th stanza branch, and added the 16th stanza.  I assigned back to you for final review if this is the last pull request.  closing this issue.
